import { DataTypes, Model } from 'sequelize';
import db from '../config/db';

class DoubtReply extends Model {
  public id!: number;
  public doubt_id!: number;
  public user_id?: number;
  public reply!: string;
  public is_instructor_reply!: boolean;
  public is_ai_reply!: boolean;
}

DoubtReply.init(
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    doubt_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    user_id: {
      type: DataTypes.INTEGER,
      allowNull: true, // null if purely generated by AI
    },
    reply: {
      type: DataTypes.TEXT,
      allowNull: false,
    },
    is_instructor_reply: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
    is_ai_reply: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
  },
  {
    sequelize: db,
    modelName: 'DoubtReply',
  }
);

export default DoubtReply;
